export const ConditionNames = 
['None'
,'Self'
,'AbilitySource'
,'OfType'
,'OfColor'
,'OfKeyword'
,'Other'
,'Friendly'
,'Opponent'
,'Player'
,'AnyTarget'
,'Creature'
,'CreatureOrPlayer'
,'Artifact'
,'Enchantment'
,'ArtifactOrEnchantment'
,'Instant'
,'Sorcery'
,'InstantOrSorcery'
,'Battle'
,'Planeswalker'
,'Library'
,'Hand'
,'TopNCardsOfLibrary'
,'PowerN'
,'CMCN'
,'ToughnessN'
,'PowerNOrGreater'
,'CMCNOrGreater'
,'ToughnessNOrGreater'
,'PowerNOrLess'
,'CMCNOrLess'
,'ToughnessNOrLess'

,'AnyFriendlyCreatureNotAttackingAndNoSummoningSickness'
] as const;

export type ConditionName = typeof ConditionNames[number]

export const ConditionSpecNames = 
['None'
,'Self'
,'AbilitySource'
,'FriendlyPlayer','OpponentPlayer','AnyPlayer','AllPlayers'
,'AnyCreature','AllCreatures','AnyOtherCreature','AllOtherCreatures'
,'AnyCreatureOrPlayer','OpponentCreatureOrPlayer'
,'AnyTarget','AllTargets'
,'AnyFriendlyCreature','AllFriendlyCreatures'
,'AnyOtherFriendlyCreature','AllOtherFriendlyCreatures'
,'AnyOpponentCreature','AllOpponentCreatures'
,'AnyArtifact','AllArtifacts'
,'AnyEnchantment','AllEnchantments'
,'AnyArtifactOrEnchantment','AllArtifactsOrEnchantments'
,'AnyTopNCardsOfFriendlyLibrary','AllTopNCardsOfFriendlyLibrary'
,'AnyTopNCardsOfOpponentLibrary','AllTopNCardsOfOpponentLibrary'
,'AnyOfType','AnyFriendlyOfType','AnyOpponentOfType','AllOfType','AllFriendlyOfType','AllOpponentOfType'
,'AnyOfColor','AnyFriendlyOfColor','AnyOpponentOfColor','AllOfColor','AllFriendlyOfColor','AllOpponentOfColor'
,'AnyOfKeyword','AnyFriendlyOfKeyword','AnyOpponentOfKeyword','AllOfKeyword','AllFriendlyOfKeyword','AllOpponentOfKeyword'
,'PowerN','AnyPowerN','AnyFriendlyPowerN','AnyOpponentPowerN','AllPowerN','AllFriendlyPowerN','AllOpponentPowerN'
,'CMCN','AnyCMCN','AnyFriendlyCMCN','AnyOpponentCMCN','AllCMCN','AllFriendlyCMCN','AllOpponentCMCN'
,'ToughnessN','AnyToughnessN','AnyFriendlyToughnessN','AnyOpponentToughnessN','AllToughnessN','AllFriendlyToughnessN','AllOpponentToughnessN'
,'PowerNOrGreater','AnyPowerNOrGreater','AnyFriendlyPowerNOrGreater','AnyOpponentPowerNOrGreater','AllPowerNOrGreater','AllFriendlyPowerNOrGreater','AllOpponentPowerNOrGreater'
,'CMCNOrGreater','AnyCMCNOrGreater','AnyFriendlyCMCNOrGreater','AnyOpponentCMCNOrGreater','AllCMCNOrGreater','AllFriendlyCMCNOrGreater','AllOpponentCMCNOrGreater'
,'ToughnessNOrGreater','AnyToughnessNOrGreater','AnyFriendlyToughnessNOrGreater','AnyOpponentToughnessNOrGreater','AllToughnessNOrGreater','AllFriendlyToughnessNOrGreater','AllOpponentToughnessNOrGreater'
,'PowerNOrLess','AnyPowerNOrLess','AnyFriendlyPowerNOrLess','AnyOpponentPowerNOrLess','AllPowerNOrLess','AllFriendlyPowerNOrLess','AllOpponentPowerNOrLess'
,'CMCNOrLess','AnyCMCNOrLess','AnyFriendlyCMCNOrLess','AnyOpponentCMCNOrLess','AllCMCNOrLess','AllFriendlyCMCNOrLess','AllOpponentCMCNOrLess'
,'ToughnessNOrLess','AnyToughnessNOrLess','AnyFriendlyToughnessNOrLess','AnyOpponentToughnessNOrLess','AllToughnessNOrLess','AllFriendlyToughnessNOrLess','AllOpponentToughnessNOrLess'
,'AnyFriendlyHand','AnyEnemyHand' //discard specifics
,'AnyFriendlyCreatureNotAttackingAndNoSummoningSickness'
] as const;

export type ConditionSpecName = typeof ConditionSpecNames[number]